TweetStampv2/Controllers/TweetController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Tweetinvi.Events;
using TweetStampv2.Models;
using TweetStampv2.Services;

namespace TweetStamp.Controllers
{
    public class TweetController : Controller
    {
        private readonly ITweetService tweetService;
      
        public TweetController(ITweetService tweetService)
        {
            this.tweetService = tweetService;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            //var accountActivityStream = handler.GetAccountActivityStream(1519700194912358400, "development");

            //accountActivityStream.MessageReceived += Webhook;
            //accountActivityStream.TweetCreated += ReplyWebhook;

            tweetService.WebhookSubscribe(Webhook, ReplyWebhook);
            return View();
        }

        [HttpGet]
        [Route("/{id}")]
        public async Task<ActionResult<TweetModel>> GetTweetById(long id)
        {
            //var tweet = context.Tweets.FirstOrDefault(t => t.Id == id);
            if (id == 0)
                return RedirectToAction("Index");

            var tweet = await tweetService.GetTweetByIdAsync(id);

            if(tweet != null)
                return View(tweet);
            return RedirectToAction("TweetNotFound");

        }

        [Route("/about")]
        public IActionResult About()
        {
            return View();
        }
        [Route("/notfound")]
        public IActionResult TweetNotFound()
        {
            return View();
        }

        [HttpPost]
        public void Webhook(object sender, MessageReceivedEvent e)
        {
            tweetService.StampTweetDM(e).Wait();

            //var messageJson = e.Json;
            //JObject jsonObj = JObject.Parse(messageJson);
            //var tweetUrl = (string)jsonObj["direct_message_events"][0]["message_create"]["message_data"]
            //    ["entities"]["urls"][0]["expanded_url"];
            //var tweetId = long.Parse(tweetUrl.Split("status/")[1].Split('?')[0]);
            //var tweet = await twitterClient.Tweets.GetTweetAsync(tweetId);

            //var tweetJson = JsonConvert.SerializeObject(tweet.TweetDTO,
            //    Formatting.None, new JsonSerializerSettings()
            //    {
            //        NullValueHandling = NullValueHandling.Ignore
            //    });


            //StringBuilder Sb = new();

            //using (var hash = SHA256.Create())
            //{

            //    Encoding enc = Encoding.UTF8;

            //    byte[] result = hash.ComputeHash(enc.GetBytes(tweetJson));
            //    var stringResult = Convert.ToHexString(result);
            //    foreach (var b in result)
            //    {
            //        Sb.Append(b.ToString("x2"));
            //    }
            //}

            //var tweetHash = Sb.ToString();

            //var senderId = long.Parse((string)jsonObj["direct_message_events"][0]["message_create"]["sender_id"]);

            //await twitterClient.Messages.PublishMessageAsync($"Here's your stringified tweet's hash: " +
            //    $"{tweetHash}", senderId);

            //var restClient = new RestClient("https://proofofexistence.com");
            //var restRequest = new RestRequest("api/v1/register", Method.Post);
            //restRequest.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            //restRequest.AddHeader("Accept", "application/json");
            //restRequest.AddBody(new { d = tweetHash });

            //var restResponse = await restClient.PostAsync(restRequest);

        }

        [HttpPost]
        public void ReplyWebhook(object sender, TweetCreatedEvent e)
        {
            tweetService.StampTweetMention(e).Wait();
            //var messageJson = e.Json;
            //JObject jsonObj = JObject.Parse(messageJson);

            //if (((string)jsonObj["tweet_create_events"][0]["text"]).ToLower().Contains("stamp"))
            //{
            //    var tweetUrl = (string)jsonObj["tweet_create_events"][0]["in_reply_to_status_id_str"];

            //    if (long.TryParse(tweetUrl, out long tweetId))
            //    {
            //        var tweet = await twitterClient.Tweets.GetTweetAsync(tweetId);

            //        var tweetJson = JsonConvert.SerializeObject(tweet.TweetDTO,
            //            Formatting.None, new JsonSerializerSettings()
            //            {
            //                NullValueHandling = NullValueHandling.Ignore
            //            });


            //        StringBuilder Sb = new();

            //        using (var hash = SHA256.Create())
            //        {

            //            Encoding enc = Encoding.UTF8;

            //            byte[] result = hash.ComputeHash(enc.GetBytes(tweetJson));
            //            var stringResult = Convert.ToHexString(result);
            //            foreach (var b in result)
            //            {
            //                Sb.Append(b.ToString("x2"));
            //            }
            //        }
            //        var tweetHash = Sb.ToString();
            //        var userName = (string)jsonObj["tweet_create_events"][0]["user"]["screen_name"];
            //        var userTweetId = (string)jsonObj["tweet_create_events"][0]["id"];
            //        var reply = await twitterClient.Tweets.PublishTweetAsync(
            //            new PublishTweetParameters($"@{userName} here's your stringified tweet's hash: " +
            //            $"{tweetHash}")
            //            {
            //                InReplyToTweetId = long.Parse(userTweetId)
            //            });

            //    }
            //}
        }

        //[HttpGet]
        //[Route("/Tweet/test")]
        //public async Task TestTweetStamp()
        //{
        //    var tweet = await tweetService.GetTweetByIdAsync(1521422674722971648);
        //    //tweetService.StampTweet(tweet.Json);
        //}


    }
}

TweetStampv2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TweetStamp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<script sync src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
	<link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700i" rel="stylesheet">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/jsonstyle.css" />
	<link rel="icon" type="image/png" href="/icons8-bitcoin-blockchain-pastel-16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="/icons8-bitcoin-blockchain-pastel-32.png" sizes="32x32" />
</head>
<body>
	<header>
		<nav class="navbar navbar-light justify-content-between" style="background-color: #3a7aa8;">
			<a style="color:white;" class="navbar-brand" asp-area="" asp-controller="Tweet" asp-action="Index">TWEETSTAMP</a>
			<span>
				<a style="color:white;" class="navbar-brand" asp-area="" asp-controller="Tweet" asp-action="About">About</a>
				<a href="" class="btn btn-primary rounded">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
						<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
					</svg>
					&#64;Tweetstamp
				</a>
			</span>
		</nav>
	</header>
	<div class="container-fluid">
		@RenderBody()
	</div>

<footer class="page-footer footer font-small stylish-color-dark pt-4 mt-4">
    <!--Footer Links-->
    <div class="container-fluid text-center text-md-left">
        <!-- Footer links -->
        <div class="row text-center text-md-left mt-3 pb-3 d-flex flex-wrap">

            <!--First column-->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 pr-3">
                <h6 class="text-uppercase mb-4 font-weight-bold tweetstamp-brand">tweetstamp.org</h6>
                <p>[Website description placeholder]</p>

            </div>
            <!--/.First column-->

            <hr class="w-100 clearfix d-md-none">
            <div class="col-md-9 d-flex flex-wrap justify-content-around">
                <div class="p-3 mt-3 text-center">
                    <h6 class="mb-3 font-weight-bold">BTC</h6>
                    <p>
                        <img class="img-responsive addys" src="~/images/bitcoin.jpg" alt="bitcoin">
                    </p>
                    <p>[Bitcoin address placeholder]</p>
                </div>
            </div>
        </div>
        <!-- Footer links -->

        <hr>

        <div class="row py-3 d-flex align-items-center">

            <!--Grid column-->
            <div class="col-md-8 col-lg-8">

                <!--Copyright-->
                <p class="text-center text-md-left grey-text">© @DateTime.Now.Year Copyright TweetStamp </p>
                <!--/.Copyright-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 col-lg-4 ml-lg-0">

            </div>
            <!--Grid column-->
        </div>
    </div>

</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>